version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build Docs
          command: npm run build -- --prefix-paths
      - persist_to_workspace:
          root: ./
          paths: public
      - store_artifacts:
          path: public

  deploy:
    docker:
      - image: node:10
    steps:
      - checkout
      # Download and cache dependencies
      - add_ssh_keys:
          fingerprints:
            - "e5:7a:f1:ea:00:f6:f3:09:eb:3e:b2:f2:9d:6a:06:f8"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - attach_workspace:
          at: public/
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "ci-build@circleci.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages -d public --message "[gatsby] Deploy docs [skip-ci]"

workflows:
  version: 2
  master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
